auto-detect: true
fallback: stone

replacements:
  "minecraft:moss_block": mossy_cobblestone
  "minecraft:moss_carpet": green_carpet
  "minecraft:pointed_dripstone": air
  "minecraft:dripstone_block": andesite
  "minecraft:decorated_pot": flower_pot
  "minecraft:observer": polished_andesite
  "minecraft:grindstone": stonecutter
  "minecraft:beehive": oak_planks
  "minecraft:bee_nest": oak_planks
  "minecraft:composter": oak_planks
  "minecraft:scaffolding": air
  "minecraft:crafter": crafting_table
  "minecraft:lodestone": polished_andesite
  "minecraft:seagrass": air
  "minecraft:kelp": air
  "minecraft:dropper": cobblestone
  "minecraft:dispenser": cobblestone
  "minecraft:piston": smooth_stone
  "minecraft:sticky_piston": smooth_stone
  "minecraft:piston_arm_collision": air
  "minecraft:sticky_piston_arm_collision": air
  "minecraft:heavy_core": polished_andesite
  "minecraft:target": red_concrete
  "minecraft:pale_moss_block": mossy_cobblestone
  "minecraft:leaf_litter": air
  "minecraft:powder_snow": snow
  "minecraft:suspicious_sand": sand
  "minecraft:suspicious_gravel": gravel
  "minecraft:honey_block": honeycomb_block
  "minecraft:sculk_shrieker": sculk
  "minecraft:sculk_catalyst": sculk
  "minecraft:sculk_sensor": sculk
  "minecraft:calibrated_sculk_sensor": sculk
  "minecraft:deprecated_anvil": anvil
  "minecraft:deprecated_purpur_block_1": purpur_block
  "minecraft:deprecated_purpur_block_2": purpur_block
  "minecraft:creaking_heart": oak_log
  "minecraft:conduit": air
  "minecraft:end_gateway": air
  "minecraft:end_portal": air
  "minecraft:bubble_column": air
  "minecraft:moving_block": air
  "minecraft:client_request_placeholder_block": air
  "minecraft:unknown": air
  "minecraft:camera": air
  "minecraft:chalkboard": air
  "minecraft:dried_ghast": air
  "minecraft:allow": barrier
  "minecraft:deny": barrier
  "minecraft:border_block": barrier
  "minecraft:jigsaw": air
  "minecraft:structure_block": air
  "minecraft:command_block": air
  "minecraft:chain_command_block": air
  "minecraft:repeating_command_block": air
  "minecraft:vault": iron_bars
  "minecraft:trial_spawner": iron_bars
